package com.example.xpandit.model;

import java.io.Serializable;
import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Movie implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2359201214561434142L;
	// Id of the movie
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	// Title of the movie
	@Column(nullable = false, unique = true)
	private String title;
	// The lunch date
	private Calendar date;
	// Rating (0 to 10)
	private Integer rank;
	// The revenue generated by the movie
	private Long revenue;

	public Movie() {
	}

	public Movie(String title, Calendar date, Integer rank, Long revenue) {
		this.title = title;
		this.date = date;
		this.rank = rank;
		this.revenue = revenue;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Calendar getDate() {
		return date;
	}

	public void setDate(Calendar date) {
		this.date = date;
	}

	public Integer getRank() {
		return rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Long getRevenue() {
		return revenue;
	}

	public void setRevenue(Long revenue) {
		this.revenue = revenue;
	}

	@Override
	public String toString() {
		return "Movie [id=" + id + ", title=" + title + ", date=" + date + ", rank=" + rank + ", revenue=" + revenue
				+ "]";
	}

}
